# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
selene = "Kampfkarren/selene@0.28.0"
rojo = "rojo-rbx/rojo@7.5.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.44.1"
stylua = "JohnnyMorganz/StyLua@2.1.0"
darklua = "seaofvoices/darklua@0.16.0"
lune = "lune-org/lune@0.8.9"
