name: Validate Commit

on:
  push:

jobs:

  validate:
    runs-on: windows-latest

    strategy:
      matrix:
        scene: [main]
        include:
          - name: main

    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      ROJO_CONFIG: "dev.project.json"
    steps:
      - uses: actions/checkout@v2

      - name: Install Tooling
        uses: CompeyDev/setup-rokit@v0.1.2
      - name: set-up lune
        run: lune setup

      - name: install wally
        run: sh scripts/wally-install.sh "${{env.ROJO_CONFIG}}"

      - name: validate project
        run: sh scripts/validate.sh "${{env.ROJO_CONFIG}}" --wally