name: Validate Commit

on:
  push:

jobs:

  validate:
    runs-on: windows-latest

    strategy:
      matrix:
        package: [
          "cloud-v1-universes-standardDatastores",
          "cloud-v1-universes-places",
          "cloud-v1-universes-orderedDatastores",
          "cloud-v1-universes-messagingService",
          "cloud-v1-assets",
          "cloud-v2-universes",
          "cloud-v2-universes-places",
        ]

    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      ROJO_CONFIG: "dev.project.json"
      PACKAGE: ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Tooling
        uses: CompeyDev/setup-rokit@v0.1.2
      - name: set-up lune
        run: lune setup
      - name: install wally
        run: sh scripts/wally-install.sh "${{env.ROJO_CONFIG}}"
      - name: validate project
        run: sh scripts/validate.sh "${{env.PACKAGE}}" --wally